### ISSUE TITLE
Almost 25 years later...

### ISSUE THREAD

**Issue by mtwagneratiu** [BrickBot/Lego-Scheme#1]
I can believe this still exists.

**Comment by mesheets** [comment]
;-)  Thanks for stopping by!  If you'd like, I can enable discussions here.

Also, if you haven't seen them already, be sure to check out the other RCX-related projects available here under [BrickBot.github.io](https://brickbot.github.io/) / [github.com/brickbot](https://github.com/BrickBot/)!

**Comment by mesheets** [comment]
We welcome you to join the discussion board!
- https://github.com/orgs/BrickBot/discussions
